name: icafe_flutter
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  dio: ^5.0.0
  intl: ^0.18.0
  http: ^1.5.0
  flutter_bloc: ^9.1.1
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  path: ^1.9.1
  cupertino_icons: ^1.0.8
  pdf: ^3.11.1
  path_provider: ^2.1.5
  open_file: ^3.5.9
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logoicafe.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
